services:
  version-monitor:
    image: darenbooth/version-monitor:v0.X
    container_name: version-monitor
    ports:
      - "8136:80"
    env_file:
      - .env
    volumes:
      - ./monitor_data:/app/data
    restart: always
