services:
  version-monitor:
    image: darenbooth/version-monitor:latest
    container_name: version-monitor
    ports:
      - "8136:80"
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN}
    volumes:
      - ./monitor_data:/app/data  # This keeps the SQLite database safe on the host
    restart: always